# Configuration spécifique pour Cloudflare Pages
# Ce fichier remplace wrangler.toml pour éviter les conflits

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

# Configuration des variables d'environnement
[env.production]
NODE_ENV = "production"

# Configuration des routes
[[routes]]
pattern = "/*"
custom_domain = false

# Configuration pour Next.js
[framework]
name = "nextjs"
version = "14.2.32"

# Variables d'environnement requises (à configurer dans le dashboard)
# DATABASE_URL = "postgresql://user:password@host:port/database"
# EDGE_AUTH_SECRET = "your-super-secret-jwt-key"
# NEXT_PUBLIC_APP_URL = "https://your-domain.pages.dev"
