name = "sneakers-ecommerce"
compatibility_date = "2024-01-01"

[env.production]
vars = { NODE_ENV = "production" }

[[env.production.routes]]
pattern = "sneakers-store.pages.dev/*"
zone_name = "pages.dev"

# Configuration pour Cloudflare Pages
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

# Variables d'environnement (à configurer dans le dashboard Cloudflare)
# DATABASE_URL = "votre-url-de-base-de-donnees"
# EDGE_AUTH_SECRET = "votre-secret-jwt"
# NEXT_PUBLIC_APP_URL = "https://votre-domaine.com"