export interface User {
  id: string
  email: string
  name: string
  role: "admin" | "seller" | "customer"
  createdAt: Date
}

export interface Product {
  id: string
  name: string
  brand: string
  price: number
  originalPrice?: number
  description: string
  images: string[]
  category: "men" | "women" | "kids"
  sizes: ProductSize[]
  colors: string[]
  featured: boolean
  isNew: boolean
  onSale: boolean
  createdAt: Date
}

export interface ProductSize {
  size: string
  stock: number
}

export interface CartItem {
  productId: string
  size: string
  quantity: number
}

export interface Order {
  id: string
  userId: string
  items: CartItem[]
  total: number
  status: "pending" | "confirmed" | "shipped" | "delivered" | "cancelled"
  shippingAddress: Address
  createdAt: Date
}

export interface Address {
  street: string
  city: string
  postalCode: string
  country: string
}

// Mock users
export const mockUsers: User[] = [
  {
    id: "1",
    email: "admin@sneakpeak.com",
    name: "Admin User",
    role: "admin",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    email: "seller@sneakpeak.com",
    name: "Seller User",
    role: "seller",
    createdAt: new Date("2024-01-15"),
  },
]

// Mock products
export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Air Jordan 1 Retro High OG",
    brand: "Nike",
    price: 179.99,
    originalPrice: 199.99,
    description: "La sneaker iconique qui a révolutionné le basketball et la street culture.",
    images: ["/air-jordan-1-black-red-sneaker.jpg", "/air-jordan-1-side-view.jpg", "/air-jordan-1-sole-view.jpg"],
    category: "men",
    sizes: [
      { size: "40", stock: 5 },
      { size: "41", stock: 3 },
      { size: "42", stock: 8 },
      { size: "43", stock: 2 },
      { size: "44", stock: 6 },
      { size: "45", stock: 4 },
      { size: "46", stock: 3 },
      { size: "47", stock: 2 },
      { size: "48", stock: 1 },
      { size: "49", stock: 1 },
      { size: "50", stock: 1 },
    ],
    colors: ["Noir/Rouge", "Blanc/Noir"],
    featured: true,
    isNew: false,
    onSale: true,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    name: "Adidas Yeezy Boost 350 V2",
    brand: "Adidas",
    price: 249.99,
    description: "Design futuriste et confort exceptionnel avec la technologie Boost.",
    images: [
      "/yeezy-boost-350-v2-cream-white-sneaker.jpg",
      "/yeezy-boost-350-v2-side-profile.jpg",
      "/yeezy-boost-350-v2-sole-detail.jpg",
    ],
    category: "men",
    sizes: [
      { size: "39", stock: 2 },
      { size: "40", stock: 4 },
      { size: "41", stock: 1 },
      { size: "42", stock: 7 },
      { size: "43", stock: 3 },
      { size: "44", stock: 2 },
      { size: "45", stock: 1 },
      { size: "46", stock: 1 },
      { size: "47", stock: 0 },
      { size: "48", stock: 1 },
      { size: "49", stock: 0 },
      { size: "50", stock: 1 },
    ],
    colors: ["Cream White", "Core Black"],
    featured: true,
    isNew: true,
    onSale: false,
    createdAt: new Date("2024-02-15"),
  },
  {
    id: "4",
    name: "New Balance 550",
    brand: "New Balance",
    price: 139.99,
    originalPrice: 159.99,
    description: "Inspiration basketball vintage avec un style intemporel et moderne.",
    images: [
      "/new-balance-550-white-green-sneaker.jpg",
      "/new-balance-550-side-view.jpg",
      "/new-balance-550-detail-view.jpg",
    ],
    category: "men",
    sizes: [
      { size: "40", stock: 6 },
      { size: "41", stock: 4 },
      { size: "42", stock: 9 },
      { size: "43", stock: 5 },
      { size: "44", stock: 3 },
      { size: "45", stock: 2 },
      { size: "46", stock: 2 },
      { size: "47", stock: 1 },
      { size: "48", stock: 1 },
      { size: "49", stock: 0 },
      { size: "50", stock: 1 },
    ],
    colors: ["Blanc/Vert", "Blanc/Gris", "Noir/Blanc"],
    featured: true,
    isNew: true,
    onSale: true,
    createdAt: new Date("2024-03-10"),
  },
  {
    id: "3",
    name: "Nike Dunk Low",
    brand: "Nike",
    price: 119.99,
    description: "Style rétro basketball revisité pour la rue.",
    images: [
      "/nike-dunk-low-white-black-panda-sneaker.jpg",
      "/nike-dunk-low-side-view.jpg",
      "/nike-dunk-low-back-view.jpg",
    ],
    category: "women",
    sizes: [
      { size: "36", stock: 4 },
      { size: "37", stock: 6 },
      { size: "38", stock: 8 },
      { size: "39", stock: 5 },
      { size: "40", stock: 3 },
      { size: "41", stock: 2 },
      { size: "42", stock: 2 },
      { size: "43", stock: 1 },
      { size: "44", stock: 1 },
      { size: "45", stock: 1 },
      { size: "46", stock: 0 },
      { size: "47", stock: 0 },
      { size: "48", stock: 1 },
      { size: "49", stock: 0 },
      { size: "50", stock: 1 },
    ],
    colors: ["Panda", "University Blue"],
    featured: false,
    isNew: false,
    onSale: false,
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "5",
    name: "Converse Chuck Taylor All Star",
    brand: "Converse",
    price: 69.99,
    description: "L'iconique sneaker intemporelle qui traverse les générations.",
    images: ["/placeholder-9d3az.png", "/placeholder-v6r6j.png", "/placeholder-hntlx.png"],
    category: "women",
    sizes: [
      { size: "36", stock: 8 },
      { size: "37", stock: 12 },
      { size: "38", stock: 15 },
      { size: "39", stock: 10 },
      { size: "40", stock: 6 },
      { size: "41", stock: 4 },
      { size: "42", stock: 3 },
      { size: "43", stock: 2 },
      { size: "44", stock: 2 },
      { size: "45", stock: 1 },
      { size: "46", stock: 1 },
      { size: "47", stock: 0 },
      { size: "48", stock: 1 },
      { size: "49", stock: 0 },
      { size: "50", stock: 1 },
    ],
    colors: ["Noir", "Blanc", "Rouge"],
    featured: false,
    isNew: false,
    onSale: false,
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "6",
    name: "Vans Old Skool",
    brand: "Vans",
    price: 79.99,
    originalPrice: 89.99,
    description: "Le classique skate avec la bande latérale iconique.",
    images: ["/placeholder-y7mwf.png", "/placeholder-uwkoa.png", "/placeholder-64oz5.png"],
    category: "women",
    sizes: [
      { size: "36", stock: 5 },
      { size: "37", stock: 8 },
      { size: "38", stock: 12 },
      { size: "39", stock: 7 },
      { size: "40", stock: 4 },
      { size: "41", stock: 3 },
      { size: "42", stock: 2 },
      { size: "43", stock: 1 },
      { size: "44", stock: 1 },
      { size: "45", stock: 1 },
      { size: "46", stock: 0 },
      { size: "47", stock: 0 },
      { size: "48", stock: 1 },
      { size: "49", stock: 0 },
      { size: "50", stock: 1 },
    ],
    colors: ["Noir/Blanc", "Bleu Marine", "Bordeaux"],
    featured: true,
    isNew: false,
    onSale: true,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "7",
    name: "Nike Air Force 1 Kids",
    brand: "Nike",
    price: 89.99,
    description: "La légendaire Air Force 1 adaptée aux plus jeunes.",
    images: ["/placeholder-tn7x1.png", "/placeholder-tpxji.png", "/placeholder-8d7v6.png"],
    category: "kids",
    sizes: [
      { size: "25", stock: 3 },
      { size: "26", stock: 5 },
      { size: "27", stock: 4 },
      { size: "28", stock: 6 },
      { size: "29", stock: 8 },
      { size: "30", stock: 10 },
      { size: "31", stock: 7 },
      { size: "32", stock: 5 },
      { size: "33", stock: 4 },
      { size: "34", stock: 3 },
      { size: "35", stock: 2 },
      { size: "36", stock: 2 },
      { size: "37", stock: 1 },
      { size: "38", stock: 1 },
      { size: "39", stock: 1 },
    ],
    colors: ["Blanc", "Noir", "Rose"],
    featured: false,
    isNew: true,
    onSale: false,
    createdAt: new Date("2024-03-05"),
  },
  {
    id: "8",
    name: "Adidas Stan Smith Kids",
    brand: "Adidas",
    price: 59.99,
    originalPrice: 69.99,
    description: "Le tennis classique revisité pour les enfants.",
    images: ["/placeholder-nmrbe.png", "/placeholder-8x7ek.png", "/placeholder-drycq.png"],
    category: "kids",
    sizes: [
      { size: "25", stock: 3 },
      { size: "26", stock: 5 },
      { size: "27", stock: 4 },
      { size: "28", stock: 7 },
      { size: "29", stock: 9 },
      { size: "30", stock: 8 },
      { size: "31", stock: 6 },
      { size: "32", stock: 3 },
      { size: "33", stock: 2 },
      { size: "34", stock: 2 },
      { size: "35", stock: 1 },
      { size: "36", stock: 1 },
      { size: "37", stock: 1 },
      { size: "38", stock: 0 },
      { size: "39", stock: 1 },
    ],
    colors: ["Blanc/Vert", "Blanc/Rose", "Blanc/Bleu"],
    featured: true,
    isNew: false,
    onSale: true,
    createdAt: new Date("2024-01-25"),
  },
  {
    id: "9",
    name: "Puma RS-X",
    brand: "Puma",
    price: 129.99,
    description: "Design futuriste et technologie de pointe pour un style unique.",
    images: ["/placeholder-4k56m.png", "/placeholder-48unl.png", "/placeholder-4qoxw.png"],
    category: "men",
    sizes: [
      { size: "40", stock: 3 },
      { size: "41", stock: 5 },
      { size: "42", stock: 7 },
      { size: "43", stock: 4 },
      { size: "44", stock: 2 },
      { size: "45", stock: 1 },
      { size: "46", stock: 1 },
      { size: "47", stock: 0 },
      { size: "48", stock: 1 },
      { size: "49", stock: 0 },
      { size: "50", stock: 1 },
    ],
    colors: ["Multicolore", "Noir/Blanc", "Bleu/Orange"],
    featured: false,
    isNew: true,
    onSale: false,
    createdAt: new Date("2024-03-15"),
  },
  {
    id: "10",
    name: "Reebok Club C 85",
    brand: "Reebok",
    price: 89.99,
    originalPrice: 109.99,
    description: "Tennis vintage avec un style épuré et intemporel.",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    category: "women",
    sizes: [
      { size: "36", stock: 6 },
      { size: "37", stock: 9 },
      { size: "38", stock: 11 },
      { size: "39", stock: 8 },
      { size: "40", stock: 5 },
      { size: "41", stock: 3 },
      { size: "42", stock: 2 },
      { size: "43", stock: 1 },
      { size: "44", stock: 1 },
      { size: "45", stock: 1 },
      { size: "46", stock: 0 },
      { size: "47", stock: 0 },
      { size: "48", stock: 1 },
      { size: "49", stock: 0 },
      { size: "50", stock: 1 },
    ],
    colors: ["Blanc", "Beige", "Rose Poudré"],
    featured: false,
    isNew: false,
    onSale: true,
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "11",
    name: "Nike Air Max 90",
    brand: "Nike",
    price: 149.99,
    description: "L'iconique Air Max avec son amorti visible révolutionnaire.",
    images: [
      "/nike-air-max-90-white-sneaker.jpg",
      "/nike-air-max-90-side-view.jpg",
      "/nike-air-max-90-sole-detail.jpg",
    ],
    category: "men",
    sizes: [
      { size: "40", stock: 7 },
      { size: "41", stock: 5 },
      { size: "42", stock: 9 },
      { size: "43", stock: 6 },
      { size: "44", stock: 4 },
      { size: "45", stock: 3 },
      { size: "46", stock: 2 },
      { size: "47", stock: 1 },
      { size: "48", stock: 2 },
      { size: "49", stock: 1 },
      { size: "50", stock: 1 },
    ],
    colors: ["Blanc/Gris", "Noir/Rouge", "Bleu/Blanc"],
    featured: true,
    isNew: false,
    onSale: false,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "12",
    name: "Adidas Ultraboost 22",
    brand: "Adidas",
    price: 189.99,
    originalPrice: 219.99,
    description: "Performance running avec technologie Boost révolutionnaire.",
    images: ["/adidas-ultraboost-22-black.jpg", "/adidas-ultraboost-22-profile.jpg", "/adidas-ultraboost-22-sole.jpg"],
    category: "men",
    sizes: [
      { size: "40", stock: 4 },
      { size: "41", stock: 6 },
      { size: "42", stock: 8 },
      { size: "43", stock: 5 },
      { size: "44", stock: 3 },
      { size: "45", stock: 2 },
      { size: "46", stock: 1 },
      { size: "47", stock: 1 },
      { size: "48", stock: 1 },
      { size: "49", stock: 0 },
      { size: "50", stock: 1 },
    ],
    colors: ["Core Black", "Cloud White", "Solar Red"],
    featured: false,
    isNew: true,
    onSale: true,
    createdAt: new Date("2024-03-20"),
  },
  {
    id: "13",
    name: "Jordan 4 Retro",
    brand: "Nike",
    price: 219.99,
    description: "Légende du basketball avec design iconique et performance.",
    images: ["/jordan-4-retro-white-cement.jpg", "/jordan-4-side-view.jpg", "/jordan-4-back-detail.jpg"],
    category: "men",
    sizes: [
      { size: "40", stock: 2 },
      { size: "41", stock: 3 },
      { size: "42", stock: 5 },
      { size: "43", stock: 4 },
      { size: "44", stock: 2 },
      { size: "45", stock: 1 },
      { size: "46", stock: 1 },
      { size: "47", stock: 0 },
      { size: "48", stock: 1 },
      { size: "49", stock: 0 },
      { size: "50", stock: 1 },
    ],
    colors: ["White Cement", "Black Cat", "University Blue"],
    featured: false,
    isNew: true,
    onSale: false,
    createdAt: new Date("2024-03-25"),
  },
  {
    id: "14",
    name: "Asics Gel-Kayano 30",
    brand: "Asics",
    price: 169.99,
    description: "Stabilité et confort pour la course longue distance.",
    images: ["/asics-gel-kayano-30-blue.jpg", "/asics-running-shoe-side.jpg", "/asics-gel-technology.jpg"],
    category: "men",
    sizes: [
      { size: "40", stock: 5 },
      { size: "41", stock: 7 },
      { size: "42", stock: 9 },
      { size: "43", stock: 6 },
      { size: "44", stock: 4 },
      { size: "45", stock: 3 },
      { size: "46", stock: 2 },
      { size: "47", stock: 1 },
      { size: "48", stock: 1 },
      { size: "49", stock: 1 },
      { size: "50", stock: 1 },
    ],
    colors: ["Midnight/Electric Blue", "Black/White", "Grey/Orange"],
    featured: false,
    isNew: false,
    onSale: false,
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "15",
    name: "Nike Blazer Mid '77",
    brand: "Nike",
    price: 109.99,
    originalPrice: 129.99,
    description: "Style vintage basketball avec une touche moderne.",
    images: ["/nike-blazer-mid-77-white.jpg", "/nike-blazer-profile-view.jpg", "/nike-blazer-vintage-style.jpg"],
    category: "women",
    sizes: [
      { size: "36", stock: 8 },
      { size: "37", stock: 10 },
      { size: "38", stock: 12 },
      { size: "39", stock: 9 },
      { size: "40", stock: 6 },
      { size: "41", stock: 4 },
      { size: "42", stock: 3 },
      { size: "43", stock: 2 },
      { size: "44", stock: 1 },
      { size: "45", stock: 1 },
      { size: "46", stock: 0 },
      { size: "47", stock: 0 },
      { size: "48", stock: 1 },
      { size: "49", stock: 0 },
      { size: "50", stock: 1 },
    ],
    colors: ["White/Black", "Vintage Green", "Pink Foam"],
    featured: false,
    isNew: false,
    onSale: true,
    createdAt: new Date("2024-01-30"),
  },
  {
    id: "16",
    name: "Adidas Samba OG",
    brand: "Adidas",
    price: 99.99,
    description: "Classique football devenu icône streetwear.",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    category: "women",
    sizes: [
      { size: "36", stock: 7 },
      { size: "37", stock: 9 },
      { size: "38", stock: 11 },
      { size: "39", stock: 8 },
      { size: "40", stock: 5 },
      { size: "41", stock: 3 },
      { size: "42", stock: 2 },
      { size: "43", stock: 1 },
      { size: "44", stock: 1 },
      { size: "45", stock: 1 },
      { size: "46", stock: 0 },
      { size: "47", stock: 0 },
      { size: "48", stock: 1 },
      { size: "49", stock: 0 },
      { size: "50", stock: 1 },
    ],
    colors: ["Core Black/White", "White/Green", "Burgundy/Gold"],
    featured: false,
    isNew: true,
    onSale: false,
    createdAt: new Date("2024-03-12"),
  },
  {
    id: "17",
    name: "New Balance 2002R",
    brand: "New Balance",
    price: 159.99,
    description: "Design Y2K revisité avec technologies modernes.",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    category: "men",
    sizes: [
      { size: "40", stock: 4 },
      { size: "41", stock: 6 },
      { size: "42", stock: 8 },
      { size: "43", stock: 5 },
      { size: "44", stock: 3 },
      { size: "45", stock: 2 },
      { size: "46", stock: 1 },
      { size: "47", stock: 1 },
      { size: "48", stock: 1 },
      { size: "49", stock: 0 },
      { size: "50", stock: 1 },
    ],
    colors: ["Rain Cloud", "Sea Salt", "Black/Silver"],
    featured: false,
    isNew: true,
    onSale: false,
    createdAt: new Date("2024-03-18"),
  },
  {
    id: "18",
    name: "Vans Sk8-Hi",
    brand: "Vans",
    price: 89.99,
    originalPrice: 99.99,
    description: "Montante iconique du skateboard avec protection cheville.",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    category: "women",
    sizes: [
      { size: "36", stock: 6 },
      { size: "37", stock: 8 },
      { size: "38", stock: 10 },
      { size: "39", stock: 7 },
      { size: "40", stock: 4 },
      { size: "41", stock: 3 },
      { size: "42", stock: 2 },
      { size: "43", stock: 1 },
      { size: "44", stock: 1 },
      { size: "45", stock: 1 },
      { size: "46", stock: 0 },
      { size: "47", stock: 0 },
      { size: "48", stock: 1 },
      { size: "49", stock: 0 },
      { size: "50", stock: 1 },
    ],
    colors: ["Black/White", "Navy/White", "Checkerboard"],
    featured: false,
    isNew: false,
    onSale: true,
    createdAt: new Date("2024-02-05"),
  },
  {
    id: "19",
    name: "Puma Suede Classic",
    brand: "Puma",
    price: 79.99,
    description: "Légende du streetwear en daim premium.",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    category: "men",
    sizes: [
      { size: "40", stock: 8 },
      { size: "41", stock: 10 },
      { size: "42", stock: 12 },
      { size: "43", stock: 9 },
      { size: "44", stock: 6 },
      { size: "45", stock: 4 },
      { size: "46", stock: 3 },
      { size: "47", stock: 2 },
      { size: "48", stock: 1 },
      { size: "49", stock: 1 },
      { size: "50", stock: 1 },
    ],
    colors: ["Peacoat/White", "Team Gold/Black", "High Risk Red/White"],
    featured: false,
    isNew: false,
    onSale: false,
    createdAt: new Date("2024-01-12"),
  },
  {
    id: "20",
    name: "Converse One Star",
    brand: "Converse",
    price: 89.99,
    originalPrice: 109.99,
    description: "Style minimaliste avec l'étoile iconique.",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    category: "women",
    sizes: [
      { size: "36", stock: 5 },
      { size: "37", stock: 7 },
      { size: "38", stock: 9 },
      { size: "39", stock: 6 },
      { size: "40", stock: 4 },
      { size: "41", stock: 2 },
      { size: "42", stock: 2 },
      { size: "43", stock: 1 },
      { size: "44", stock: 1 },
      { size: "45", stock: 1 },
      { size: "46", stock: 0 },
      { size: "47", stock: 0 },
      { size: "48", stock: 1 },
      { size: "49", stock: 0 },
      { size: "50", stock: 1 },
    ],
    colors: ["White/Navy", "Black/White", "Vintage Khaki"],
    featured: false,
    isNew: false,
    onSale: true,
    createdAt: new Date("2024-02-25"),
  },
  {
    id: "21",
    name: "Nike React Element 55",
    brand: "Nike",
    price: 139.99,
    description: "Design futuriste avec amorti React révolutionnaire.",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    category: "men",
    sizes: [
      { size: "40", stock: 3 },
      { size: "41", stock: 5 },
      { size: "42", stock: 7 },
      { size: "43", stock: 4 },
      { size: "44", stock: 2 },
      { size: "45", stock: 1 },
      { size: "46", stock: 1 },
      { size: "47", stock: 0 },
      { size: "48", stock: 1 },
      { size: "49", stock: 0 },
      { size: "50", stock: 1 },
    ],
    colors: ["Black/Dark Grey", "White/Pure Platinum", "Game Royal/Orange"],
    featured: false,
    isNew: true,
    onSale: false,
    createdAt: new Date("2024-03-22"),
  },
  {
    id: "22",
    name: "Nike Air Max 270",
    brand: "Nike",
    price: 159.99,
    originalPrice: 179.99,
    description: "Amorti Air Max le plus volumineux pour un confort maximal.",
    images: ["/nike-air-max-270-black-white-sneaker.jpg", "/nike-air-max-270-side-profile.jpg", "/nike-air-max-270-sole-detail.jpg"],
    category: "men",
    sizes: [
      { size: "40", stock: 6 },
      { size: "41", stock: 8 },
      { size: "42", stock: 10 },
      { size: "43", stock: 7 },
      { size: "44", stock: 5 },
      { size: "45", stock: 3 },
      { size: "46", stock: 2 },
      { size: "47", stock: 1 },
      { size: "48", stock: 2 },
      { size: "49", stock: 1 },
      { size: "50", stock: 1 },
    ],
    colors: ["Black/White", "Triple White", "University Red"],
    featured: false,
    isNew: false,
    onSale: true,
    createdAt: new Date("2024-02-28"),
  },
  {
    id: "23",
    name: "Adidas NMD R1",
    brand: "Adidas",
    price: 149.99,
    description: "Style urbain moderne avec technologie Boost.",
    images: ["/adidas-nmd-r1-core-black-sneaker.jpg", "/adidas-nmd-r1-side-view.jpg", "/adidas-nmd-r1-boost-sole.jpg"],
    category: "men",
    sizes: [
      { size: "40", stock: 5 },
      { size: "41", stock: 7 },
      { size: "42", stock: 9 },
      { size: "43", stock: 6 },
      { size: "44", stock: 4 },
      { size: "45", stock: 2 },
      { size: "46", stock: 1 },
      { size: "47", stock: 1 },
      { size: "48", stock: 1 },
      { size: "49", stock: 0 },
      { size: "50", stock: 1 },
    ],
    colors: ["Core Black", "Cloud White", "Solar Red"],
    featured: false,
    isNew: true,
    onSale: false,
    createdAt: new Date("2024-03-28"),
  },
  {
    id: "24",
    name: "Nike Air Force 1 Shadow",
    brand: "Nike",
    price: 119.99,
    originalPrice: 139.99,
    description: "Version féminine revisitée de l'iconique Air Force 1.",
    images: ["/nike-air-force-1-shadow-white-pink-women-sneaker.jpg", "/nike-air-force-1-shadow-side-profile.jpg", "/nike-air-force-1-shadow-layered-design.jpg"],
    category: "women",
    sizes: [
      { size: "36", stock: 9 },
      { size: "37", stock: 12 },
      { size: "38", stock: 15 },
      { size: "39", stock: 11 },
      { size: "40", stock: 8 },
      { size: "41", stock: 5 },
      { size: "42", stock: 3 },
      { size: "43", stock: 2 },
      { size: "44", stock: 1 },
      { size: "45", stock: 1 },
      { size: "46", stock: 0 },
      { size: "47", stock: 0 },
      { size: "48", stock: 1 },
      { size: "49", stock: 0 },
      { size: "50", stock: 1 },
    ],
    colors: ["White/Pink", "Pale Ivory", "Black/White"],
    featured: false,
    isNew: false,
    onSale: true,
    createdAt: new Date("2024-02-14"),
  },
  {
    id: "25",
    name: "Adidas Gazelle",
    brand: "Adidas",
    price: 99.99,
    description: "Classique intemporel en daim premium.",
    images: ["/adidas-gazelle-pink-suede-women-sneaker.jpg", "/adidas-gazelle-side-view.jpg", "/adidas-gazelle-suede-texture-detail.jpg"],
    category: "women",
    sizes: [
      { size: "36", stock: 8 },
      { size: "37", stock: 10 },
      { size: "38", stock: 12 },
      { size: "39", stock: 9 },
      { size: "40", stock: 6 },
      { size: "41", stock: 4 },
      { size: "42", stock: 2 },
      { size: "43", stock: 1 },
      { size: "44", stock: 1 },
      { size: "45", stock: 1 },
      { size: "46", stock: 0 },
      { size: "47", stock: 0 },
      { size: "48", stock: 1 },
      { size: "49", stock: 0 },
      { size: "50", stock: 1 },
    ],
    colors: ["Pink/White", "Core Black", "Wonder Beige"],
    featured: false,
    isNew: true,
    onSale: false,
    createdAt: new Date("2024-03-30"),
  },
  {
    id: "26",
    name: "New Balance 327",
    brand: "New Balance",
    price: 89.99,
    originalPrice: 109.99,
    description: "Design rétro 70s avec une touche contemporaine.",
    images: ["/new-balance-327-grey-orange-women-sneaker.jpg", "/new-balance-327-retro-profile.jpg", "/new-balance-327-vintage-sole.jpg"],
    category: "women",
    sizes: [
      { size: "36", stock: 7 },
      { size: "37", stock: 9 },
      { size: "38", stock: 11 },
      { size: "39", stock: 8 },
      { size: "40", stock: 5 },
      { size: "41", stock: 3 },
      { size: "42", stock: 2 },
      { size: "43", stock: 1 },
      { size: "44", stock: 1 },
      { size: "45", stock: 1 },
      { size: "46", stock: 0 },
      { size: "47", stock: 0 },
      { size: "48", stock: 1 },
      { size: "49", stock: 0 },
      { size: "50", stock: 1 },
    ],
    colors: ["Grey/Orange", "White/Green", "Black/Red"],
    featured: false,
    isNew: false,
    onSale: true,
    createdAt: new Date("2024-02-18"),
  },
  {
    id: "27",
    name: "Converse Chuck Taylor All Star Kids",
    brand: "Converse",
    price: 49.99,
    description: "L'iconique Chuck Taylor adapté aux plus jeunes.",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    category: "kids",
    sizes: [
      { size: "25", stock: 4 },
      { size: "26", stock: 6 },
      { size: "27", stock: 5 },
      { size: "28", stock: 8 },
      { size: "29", stock: 10 },
      { size: "30", stock: 12 },
      { size: "31", stock: 9 },
      { size: "32", stock: 6 },
      { size: "33", stock: 4 },
      { size: "34", stock: 3 },
      { size: "35", stock: 2 },
      { size: "36", stock: 2 },
      { size: "37", stock: 1 },
      { size: "38", stock: 1 },
      { size: "39", stock: 1 },
    ],
    colors: ["Rainbow", "Pink/White", "Blue/White"],
    featured: false,
    isNew: true,
    onSale: false,
    createdAt: new Date("2024-03-26"),
  },
  {
    id: "28",
    name: "Vans Old Skool Kids",
    brand: "Vans",
    price: 59.99,
    originalPrice: 69.99,
    description: "Le classique skate en version enfant.",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    category: "kids",
    sizes: [
      { size: "25", stock: 3 },
      { size: "26", stock: 5 },
      { size: "27", stock: 4 },
      { size: "28", stock: 7 },
      { size: "29", stock: 9 },
      { size: "30", stock: 8 },
      { size: "31", stock: 6 },
      { size: "32", stock: 4 },
      { size: "33", stock: 3 },
      { size: "34", stock: 2 },
      { size: "35", stock: 2 },
      { size: "36", stock: 1 },
      { size: "37", stock: 1 },
      { size: "38", stock: 0 },
      { size: "39", stock: 1 },
    ],
    colors: ["Black/White", "Navy/White", "Red/White"],
    featured: false,
    isNew: false,
    onSale: true,
    createdAt: new Date("2024-02-22"),
  },
  {
    id: "29",
    name: "Puma Cali Kids",
    brand: "Puma",
    price: 69.99,
    description: "Style californien décontracté pour enfants.",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    category: "kids",
    sizes: [
      { size: "25", stock: 4 },
      { size: "26", stock: 6 },
      { size: "27", stock: 5 },
      { size: "28", stock: 8 },
      { size: "29", stock: 10 },
      { size: "30", stock: 9 },
      { size: "31", stock: 7 },
      { size: "32", stock: 5 },
      { size: "33", stock: 3 },
      { size: "34", stock: 2 },
      { size: "35", stock: 2 },
      { size: "36", stock: 1 },
      { size: "37", stock: 1 },
      { size: "38", stock: 1 },
      { size: "39", stock: 1 },
    ],
    colors: ["White/Pink", "White/Purple", "Black/Gold"],
    featured: false,
    isNew: true,
    onSale: false,
    createdAt: new Date("2024-03-24"),
  },
  {
    id: "30",
    name: "Nike Cortez",
    brand: "Nike",
    price: 79.99,
    originalPrice: 99.99,
    description: "Légende du running devenue icône lifestyle.",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    category: "men",
    sizes: [
      { size: "40", stock: 8 },
      { size: "41", stock: 10 },
      { size: "42", stock: 12 },
      { size: "43", stock: 9 },
      { size: "44", stock: 6 },
      { size: "45", stock: 4 },
      { size: "46", stock: 3 },
      { size: "47", stock: 2 },
      { size: "48", stock: 1 },
      { size: "49", stock: 1 },
      { size: "50", stock: 1 },
    ],
    colors: ["White/Red/Blue", "Triple White", "Black/White"],
    featured: false,
    isNew: false,
    onSale: true,
    createdAt: new Date("2024-01-18"),
  },
  {
    id: "31",
    name: "Adidas Superstar",
    brand: "Adidas",
    price: 89.99,
    originalPrice: 109.99,
    description: "Shell toe iconique, légende du streetwear.",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    category: "women",
    sizes: [
      { size: "36", stock: 10 },
      { size: "37", stock: 12 },
      { size: "38", stock: 14 },
      { size: "39", stock: 11 },
      { size: "40", stock: 8 },
      { size: "41", stock: 5 },
      { size: "42", stock: 3 },
      { size: "43", stock: 2 },
      { size: "44", stock: 1 },
      { size: "45", stock: 1 },
      { size: "46", stock: 0 },
      { size: "47", stock: 0 },
      { size: "48", stock: 1 },
      { size: "49", stock: 0 },
      { size: "50", stock: 1 },
    ],
    colors: ["White/Black", "Core Black", "Pink/White"],
    featured: false,
    isNew: false,
    onSale: true,
    createdAt: new Date("2024-01-22"),
  },
  {
    id: "32",
    name: "Nike Zoom Freak 5",
    brand: "Nike",
    price: 129.99,
    description: "Performance basketball signature Giannis Antetokounmpo.",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    category: "men",
    sizes: [
      { size: "40", stock: 4 },
      { size: "41", stock: 6 },
      { size: "42", stock: 8 },
      { size: "43", stock: 5 },
      { size: "44", stock: 3 },
      { size: "45", stock: 2 },
      { size: "46", stock: 1 },
      { size: "47", stock: 1 },
      { size: "48", stock: 1 },
      { size: "49", stock: 0 },
      { size: "50", stock: 1 },
    ],
    colors: ["Multicolor", "Black/White", "Team Colors"],
    featured: false,
    isNew: true,
    onSale: false,
    createdAt: new Date("2024-04-01"),
  },
  {
    id: "33",
    name: "Adidas Forum Low",
    brand: "Adidas",
    price: 109.99,
    description: "Basketball vintage avec strap iconique.",
    images: [
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
      "/placeholder.svg?height=400&width=400",
    ],
    category: "women",
    sizes: [
      { size: "36", stock: 6 },
      { size: "37", stock: 8 },
      { size: "38", stock: 10 },
      { size: "39", stock: 7 },
      { size: "40", stock: 5 },
      { size: "41", stock: 3 },
      { size: "42", stock: 2 },
      { size: "43", stock: 1 },
      { size: "44", stock: 1 },
      { size: "45", stock: 1 },
      { size: "46", stock: 0 },
      { size: "47", stock: 0 },
      { size: "48", stock: 1 },
      { size: "49", stock: 0 },
      { size: "50", stock: 1 },
    ],
    colors: ["White/Green", "Cloud White", "Core Black"],
    featured: false,
    isNew: true,
    onSale: false,
    createdAt: new Date("2024-04-03"),
  },
]

// Mock orders
export const mockOrders: Order[] = [
  {
    id: "ORD-001",
    userId: "2",
    items: [
      { productId: "1", size: "42", quantity: 1 },
      { productId: "3", size: "38", quantity: 2 },
    ],
    total: 419.97,
    status: "confirmed",
    shippingAddress: {
      street: "123 Rue de la Paix",
      city: "Paris",
      postalCode: "75001",
      country: "France",
    },
    createdAt: new Date("2024-03-01"),
  },
]
